name: qr_andromeda
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.1.0
  formz: ^0.8.0
  go_router: ^15.1.2
  image_gallery_saver_plus: ^4.0.1
  intl: ^0.20.2
  isar:
    hosted: https://pub.isar-community.dev
    version: 3.1.8
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev
    version: 3.1.8
  mobile_scanner: ^7.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  pretty_qr_code: ^3.4.0
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  isar_generator:
    hosted: https://pub.isar-community.dev
    version: 3.1.8

flutter:
  uses-material-design: true
  assets:
    - assets/svg/home_icons/
    - assets/svg/generate_qr_icons/
    - assets/svg/settings/
    - assets/svg/history/
    - assets/svg/open_show/
    - assets/img/
